version: "3.7"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "avansys_test"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: "mysql"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
    ports:
      - "8080:80"
    depends_on:
      - mysql
  avansys:
    container_name: avansys
    build: ./teste-avansys
    depends_on:
      - mysql
    command:
       bash -c "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    volumes:
      - ./teste-avansys:/app
      - ./teste-avansys/.env-docker:/app/.env
      - /app/vendor
